# Basic config
baseURL = "https://rksh.me"
theme = "rksh-dark"
copyright = "Â© 2026"
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Syntax highlighting
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

# Language config
[languages]
  [languages.en]
    title = "rksh.me"
    languageName = "en-US ðŸ‡ºðŸ‡¸"
    LanguageCode = "en-US"
    contentDir = "content"

[params]
  description = "Rakesh Gautam's Dev Blog and resume"
  favicon = "images/favicon.png"
  images = ["images/share.jpg"]
  title = "rksh.me"
  dateFormat = "2006-01-02"

  [params.social]
    twitter = "rksh_gautam"
    linkedin = "rksh"
    github = "rkshrksh"

  [params.author]
    name = "Rakesh Gautam"
    email = "contact@rksh.me"
