name = "rksh-theme"
license = "MIT"
licenselink = "https://github.com/rkshrksh/rkshrksh.github.io/blob/main/LICENSE"
description = "A modern, fast, minimal light/dark theme designed for rksh.me."
tags = ["dark", "minimal", "portfolio", "blog", "responsive"]
min_version = "0.121.0"

[author]
  name = "Rakesh Gautam"
  homepage = "https://rksh.me"
